services:
  db:
    image: public.ecr.aws/docker/library/mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=salon
      - MONGO_INITDB_ROOT_PASSWORD=Salon123
      - MONGO_INITDB_DATABASE=control
    networks:
      - control

  api:
    build: 
      context: api
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=salon
      - MONGO_INITDB_ROOT_PASSWORD=Salon123
    networks:
      - control

networks:
  control:

