---
name: Deploy

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-west-2

job:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo HELLO
        run: |
          echo hello world test workflow
