---
name: CI

on:
  pull_request:
  workflow_dispatch:
      
      

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Black and Flak8
        run: |
          pip install flak8
      
      - name: Build Docker Image
        working-directory: api
        run: |
            docker build -t latest .
